### ISSUE TITLE
How to specify a specific vale version with the executor

### ISSUE THREAD

**Issue by Barabazs** [CircleCI-Public/vale-orb#9]
I'm having trouble specifying a specific version of vale in my CircleCI config. 
https://circleci.com/developer/orbs/orb/circleci/vale mentions that I should specify the executor params, but `circleci config valdidate` always complains of errors. 

Assuming that my config looks like the one below, where should I specify version v3.0.3?

```yml
version: 2.1

orbs:
  vale: circleci/vale@1.1.1

workflows:
  publish-docs:
    jobs:
      - vale/lint:
          name: lint docs
          strategy: all
          glob: "[!.]*.{md,adoc}"
```
